# Generated by Django 6.0.4 on 2026-04-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_approvaldecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=160)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('result_text', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('workstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='desk.workstream')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
