# Generated by Django 6.0.4 on 2026-04-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0004_agentrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=80)),
                ('model_id', models.CharField(max_length=160)),
                ('input_per_1k_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('output_per_1k_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'model_id'],
                'unique_together': {('provider', 'model_id')},
            },
        ),
    ]
