# Generated by Django 6.0.4 on 2026-04-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0005_pricingprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='abort_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mission',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('aborted', 'Aborted')], db_index=True, default='queued', max_length=20),
        ),
    ]
