# Generated by Django 6.0.4 on 2026-04-13 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_default_organization(apps, _schema_editor):
    Organization = apps.get_model("desk", "Organization")
    AgentTemplate = apps.get_model("desk", "AgentTemplate")
    Mission = apps.get_model("desk", "Mission")
    PricingProfile = apps.get_model("desk", "PricingProfile")
    AuditLog = apps.get_model("desk", "AuditLog")
    organization, _ = Organization.objects.get_or_create(slug="default", defaults={"name": "Default OPC"})
    AgentTemplate.objects.filter(organization__isnull=True).update(organization=organization)
    Mission.objects.filter(organization__isnull=True).update(organization=organization)
    PricingProfile.objects.filter(organization__isnull=True).update(organization=organization)
    AuditLog.objects.filter(organization__isnull=True).update(organization=organization)


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0007_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FounderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder_profile', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='desk.organization')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pricingprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agenttemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_templates', to='desk.organization'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='desk.organization'),
        ),
        migrations.AddField(
            model_name='mission',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='desk.organization'),
        ),
        migrations.AddField(
            model_name='pricingprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_profiles', to='desk.organization'),
        ),
        migrations.RunPython(seed_default_organization, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='pricingprofile',
            unique_together={('organization', 'provider', 'model_id')},
        ),
    ]
