# Generated by Django 6.0.4 on 2026-04-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0008_organization_founderprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('founder', 'Founder'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='founder', max_length=20),
        ),
    ]
